
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global

[<assembly: Android.Runtime.ResourceDesignerAttribute("XamarinForms.Reactive.Samples.Droid.Resource", IsApplication=true)>]
do ()
namespace XamarinForms.Reactive.Samples.Droid
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnException4476e17c26aa42ab8fc5176c07a914b3 of obj
    exception ReturnNoneException4476e17c26aa42ab8fc5176c07a914b3
    [<AutoOpen>]
    module FuncConvertFinalOverload4476e17c26aa42ab8fc5176c07a914b3 =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            static member UpdateIdValues  () =
                global.Splat.Resource.String.library_name <- Resource_String.library_name


    
    and
        
        (* partial *)Resource_Attribute () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f010010
            static member ambientEnabled = 2130771984
            
            // aapt resource value: 0x7f01001a
            static member buttonSize = 2130771994
            
            // aapt resource value: 0x7f010001
            static member cameraBearing = 2130771969
            
            // aapt resource value: 0x7f010012
            static member cameraMaxZoomPreference = 2130771986
            
            // aapt resource value: 0x7f010011
            static member cameraMinZoomPreference = 2130771985
            
            // aapt resource value: 0x7f010002
            static member cameraTargetLat = 2130771970
            
            // aapt resource value: 0x7f010003
            static member cameraTargetLng = 2130771971
            
            // aapt resource value: 0x7f010004
            static member cameraTilt = 2130771972
            
            // aapt resource value: 0x7f010005
            static member cameraZoom = 2130771973
            
            // aapt resource value: 0x7f010019
            static member circleCrop = 2130771993
            
            // aapt resource value: 0x7f01001b
            static member colorScheme = 2130771995
            
            // aapt resource value: 0x7f010018
            static member imageAspectRatio = 2130771992
            
            // aapt resource value: 0x7f010017
            static member imageAspectRatioAdjust = 2130771991
            
            // aapt resource value: 0x7f010015
            static member latLngBoundsNorthEastLatitude = 2130771989
            
            // aapt resource value: 0x7f010016
            static member latLngBoundsNorthEastLongitude = 2130771990
            
            // aapt resource value: 0x7f010013
            static member latLngBoundsSouthWestLatitude = 2130771987
            
            // aapt resource value: 0x7f010014
            static member latLngBoundsSouthWestLongitude = 2130771988
            
            // aapt resource value: 0x7f010006
            static member liteMode = 2130771974
            
            // aapt resource value: 0x7f010000
            static member mapType = 2130771968
            
            // aapt resource value: 0x7f01001c
            static member scopeUris = 2130771996
            
            // aapt resource value: 0x7f010007
            static member uiCompass = 2130771975
            
            // aapt resource value: 0x7f01000f
            static member uiMapToolbar = 2130771983
            
            // aapt resource value: 0x7f010008
            static member uiRotateGestures = 2130771976
            
            // aapt resource value: 0x7f010009
            static member uiScrollGestures = 2130771977
            
            // aapt resource value: 0x7f01000a
            static member uiTiltGestures = 2130771978
            
            // aapt resource value: 0x7f01000b
            static member uiZoomControls = 2130771979
            
            // aapt resource value: 0x7f01000c
            static member uiZoomGestures = 2130771980
            
            // aapt resource value: 0x7f01000d
            static member useViewLifecycle = 2130771981
            
            // aapt resource value: 0x7f01000e
            static member zOrderOnTop = 2130771982
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Color () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f060008
            static member common_google_signin_btn_text_dark = 2131099656
            
            // aapt resource value: 0x7f060000
            static member common_google_signin_btn_text_dark_default = 2131099648
            
            // aapt resource value: 0x7f060001
            static member common_google_signin_btn_text_dark_disabled = 2131099649
            
            // aapt resource value: 0x7f060002
            static member common_google_signin_btn_text_dark_focused = 2131099650
            
            // aapt resource value: 0x7f060003
            static member common_google_signin_btn_text_dark_pressed = 2131099651
            
            // aapt resource value: 0x7f060009
            static member common_google_signin_btn_text_light = 2131099657
            
            // aapt resource value: 0x7f060004
            static member common_google_signin_btn_text_light_default = 2131099652
            
            // aapt resource value: 0x7f060005
            static member common_google_signin_btn_text_light_disabled = 2131099653
            
            // aapt resource value: 0x7f060006
            static member common_google_signin_btn_text_light_focused = 2131099654
            
            // aapt resource value: 0x7f060007
            static member common_google_signin_btn_text_light_pressed = 2131099655
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Drawable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f020000
            static member common_full_open_on_phone = 2130837504
            
            // aapt resource value: 0x7f020001
            static member common_google_signin_btn_icon_dark = 2130837505
            
            // aapt resource value: 0x7f020002
            static member common_google_signin_btn_icon_dark_disabled = 2130837506
            
            // aapt resource value: 0x7f020003
            static member common_google_signin_btn_icon_dark_focused = 2130837507
            
            // aapt resource value: 0x7f020004
            static member common_google_signin_btn_icon_dark_normal = 2130837508
            
            // aapt resource value: 0x7f020005
            static member common_google_signin_btn_icon_dark_pressed = 2130837509
            
            // aapt resource value: 0x7f020006
            static member common_google_signin_btn_icon_light = 2130837510
            
            // aapt resource value: 0x7f020007
            static member common_google_signin_btn_icon_light_disabled = 2130837511
            
            // aapt resource value: 0x7f020008
            static member common_google_signin_btn_icon_light_focused = 2130837512
            
            // aapt resource value: 0x7f020009
            static member common_google_signin_btn_icon_light_normal = 2130837513
            
            // aapt resource value: 0x7f02000a
            static member common_google_signin_btn_icon_light_pressed = 2130837514
            
            // aapt resource value: 0x7f02000b
            static member common_google_signin_btn_text_dark = 2130837515
            
            // aapt resource value: 0x7f02000c
            static member common_google_signin_btn_text_dark_disabled = 2130837516
            
            // aapt resource value: 0x7f02000d
            static member common_google_signin_btn_text_dark_focused = 2130837517
            
            // aapt resource value: 0x7f02000e
            static member common_google_signin_btn_text_dark_normal = 2130837518
            
            // aapt resource value: 0x7f02000f
            static member common_google_signin_btn_text_dark_pressed = 2130837519
            
            // aapt resource value: 0x7f020010
            static member common_google_signin_btn_text_light = 2130837520
            
            // aapt resource value: 0x7f020011
            static member common_google_signin_btn_text_light_disabled = 2130837521
            
            // aapt resource value: 0x7f020012
            static member common_google_signin_btn_text_light_focused = 2130837522
            
            // aapt resource value: 0x7f020013
            static member common_google_signin_btn_text_light_normal = 2130837523
            
            // aapt resource value: 0x7f020014
            static member common_google_signin_btn_text_light_pressed = 2130837524
            
            // aapt resource value: 0x7f020015
            static member Icon = 2130837525
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Id () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f07000d
            static member MyButton = 2131165197
            
            // aapt resource value: 0x7f070005
            static member adjust_height = 2131165189
            
            // aapt resource value: 0x7f070006
            static member adjust_width = 2131165190
            
            // aapt resource value: 0x7f07000a
            static member auto = 2131165194
            
            // aapt resource value: 0x7f07000b
            static member dark = 2131165195
            
            // aapt resource value: 0x7f070000
            static member hybrid = 2131165184
            
            // aapt resource value: 0x7f070007
            static member icon_only = 2131165191
            
            // aapt resource value: 0x7f07000c
            static member light = 2131165196
            
            // aapt resource value: 0x7f070001
            static member none = 2131165185
            
            // aapt resource value: 0x7f070002
            static member normal = 2131165186
            
            // aapt resource value: 0x7f070003
            static member satellite = 2131165187
            
            // aapt resource value: 0x7f070008
            static member standard = 2131165192
            
            // aapt resource value: 0x7f070004
            static member terrain = 2131165188
            
            // aapt resource value: 0x7f070009
            static member wide = 2131165193
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Integer () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f040000
            static member google_play_services_version = 2130968576
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Layout () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f030000
            static member Main = 2130903040
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_String () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f050013
            static member ApplicationName = 2131034131
            
            // aapt resource value: 0x7f050012
            static member Hello = 2131034130
            
            // aapt resource value: 0x7f050001
            static member common_google_play_services_enable_button = 2131034113
            
            // aapt resource value: 0x7f050002
            static member common_google_play_services_enable_text = 2131034114
            
            // aapt resource value: 0x7f050003
            static member common_google_play_services_enable_title = 2131034115
            
            // aapt resource value: 0x7f050004
            static member common_google_play_services_install_button = 2131034116
            
            // aapt resource value: 0x7f050005
            static member common_google_play_services_install_text = 2131034117
            
            // aapt resource value: 0x7f050006
            static member common_google_play_services_install_title = 2131034118
            
            // aapt resource value: 0x7f050007
            static member common_google_play_services_notification_ticker = 2131034119
            
            // aapt resource value: 0x7f050000
            static member common_google_play_services_unknown_issue = 2131034112
            
            // aapt resource value: 0x7f050008
            static member common_google_play_services_unsupported_text = 2131034120
            
            // aapt resource value: 0x7f050009
            static member common_google_play_services_update_button = 2131034121
            
            // aapt resource value: 0x7f05000a
            static member common_google_play_services_update_text = 2131034122
            
            // aapt resource value: 0x7f05000b
            static member common_google_play_services_update_title = 2131034123
            
            // aapt resource value: 0x7f05000c
            static member common_google_play_services_updating_text = 2131034124
            
            // aapt resource value: 0x7f05000d
            static member common_google_play_services_wear_update_text = 2131034125
            
            // aapt resource value: 0x7f05000e
            static member common_open_on_phone = 2131034126
            
            // aapt resource value: 0x7f05000f
            static member common_signin_button_text = 2131034127
            
            // aapt resource value: 0x7f050010
            static member common_signin_button_text_long = 2131034128
            
            // aapt resource value: 0x7f050011
            static member library_name = 2131034129
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Styleable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private LoadingImageView:int[]
            
            // aapt resource value: 2
            static member LoadingImageView_circleCrop = 2
            
            // aapt resource value: 1
            static member LoadingImageView_imageAspectRatio = 1
            
            // aapt resource value: 0
            static member LoadingImageView_imageAspectRatioAdjust = 0
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private MapAttrs:int[]
            
            // aapt resource value: 16
            static member MapAttrs_ambientEnabled = 16
            
            // aapt resource value: 1
            static member MapAttrs_cameraBearing = 1
            
            // aapt resource value: 18
            static member MapAttrs_cameraMaxZoomPreference = 18
            
            // aapt resource value: 17
            static member MapAttrs_cameraMinZoomPreference = 17
            
            // aapt resource value: 2
            static member MapAttrs_cameraTargetLat = 2
            
            // aapt resource value: 3
            static member MapAttrs_cameraTargetLng = 3
            
            // aapt resource value: 4
            static member MapAttrs_cameraTilt = 4
            
            // aapt resource value: 5
            static member MapAttrs_cameraZoom = 5
            
            // aapt resource value: 21
            static member MapAttrs_latLngBoundsNorthEastLatitude = 21
            
            // aapt resource value: 22
            static member MapAttrs_latLngBoundsNorthEastLongitude = 22
            
            // aapt resource value: 19
            static member MapAttrs_latLngBoundsSouthWestLatitude = 19
            
            // aapt resource value: 20
            static member MapAttrs_latLngBoundsSouthWestLongitude = 20
            
            // aapt resource value: 6
            static member MapAttrs_liteMode = 6
            
            // aapt resource value: 0
            static member MapAttrs_mapType = 0
            
            // aapt resource value: 7
            static member MapAttrs_uiCompass = 7
            
            // aapt resource value: 15
            static member MapAttrs_uiMapToolbar = 15
            
            // aapt resource value: 8
            static member MapAttrs_uiRotateGestures = 8
            
            // aapt resource value: 9
            static member MapAttrs_uiScrollGestures = 9
            
            // aapt resource value: 10
            static member MapAttrs_uiTiltGestures = 10
            
            // aapt resource value: 11
            static member MapAttrs_uiZoomControls = 11
            
            // aapt resource value: 12
            static member MapAttrs_uiZoomGestures = 12
            
            // aapt resource value: 13
            static member MapAttrs_useViewLifecycle = 13
            
            // aapt resource value: 14
            static member MapAttrs_zOrderOnTop = 14
            
            [<Microsoft.FSharp.Core.DefaultValueAttribute(false)>]
            static val mutable private SignInButton:int[]
            
            // aapt resource value: 0
            static member SignInButton_buttonSize = 0
            
            // aapt resource value: 1
            static member SignInButton_colorScheme = 1
            
            // aapt resource value: 2
            static member SignInButton_scopeUris = 2
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)

