
//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace global

[<assembly: Android.Runtime.ResourceDesignerAttribute("XamarinForms.Reactive.Sample.Places.Droid.Resource", IsApplication=true)>]
do ()
namespace XamarinForms.Reactive.Sample.Places.Droid
    // Generated by F# CodeDom
    #nowarn "49" // uppercase argument names
    #nowarn "67" // this type test or downcast will always hold
    #nowarn "66" // this upcast is unnecessary - the types are identical
    #nowarn "58" // possible incorrect indentation..
    #nowarn "57" // do not use create_DelegateEvent
    #nowarn "51" // address-of operator can occur in the code
    #nowarn "1183" // unused 'this' reference
    
    exception ReturnExceptionb0b00a187b024fbdac6a418bcf884aee of obj
    exception ReturnNoneExceptionb0b00a187b024fbdac6a418bcf884aee
    [<AutoOpen>]
    module FuncConvertFinalOverloadb0b00a187b024fbdac6a418bcf884aee =
      // This extension member adds to the FuncConvert type and is the last resort member in the method overloading rules. 
      type global.Microsoft.FSharp.Core.FuncConvert with
          /// A utility function to convert function values from tupled to curried form
          static member FuncFromTupled (f:'T -> 'Res) = f
    
    type
        [<System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")>]
        
        (* partial *)Resource () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)
            static member UpdateIdValues  () =
                global.Splat.Resource.String.library_name <- Resource_String.library_name


    
    and
        
        (* partial *)Resource_Attribute () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Color () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f050000
            static member place_autocomplete_prediction_primary_text = 2131034112
            
            // aapt resource value: 0x7f050001
            static member place_autocomplete_prediction_primary_text_highlight = 2131034113
            
            // aapt resource value: 0x7f050002
            static member place_autocomplete_prediction_secondary_text = 2131034114
            
            // aapt resource value: 0x7f050003
            static member place_autocomplete_search_hint = 2131034115
            
            // aapt resource value: 0x7f050004
            static member place_autocomplete_search_text = 2131034116
            
            // aapt resource value: 0x7f050005
            static member place_autocomplete_separator = 2131034117
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Dimension () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f060000
            static member place_autocomplete_button_padding = 2131099648
            
            // aapt resource value: 0x7f060001
            static member place_autocomplete_powered_by_google_height = 2131099649
            
            // aapt resource value: 0x7f060002
            static member place_autocomplete_powered_by_google_start = 2131099650
            
            // aapt resource value: 0x7f060003
            static member place_autocomplete_prediction_height = 2131099651
            
            // aapt resource value: 0x7f060004
            static member place_autocomplete_prediction_horizontal_margin = 2131099652
            
            // aapt resource value: 0x7f060005
            static member place_autocomplete_prediction_primary_text = 2131099653
            
            // aapt resource value: 0x7f060006
            static member place_autocomplete_prediction_secondary_text = 2131099654
            
            // aapt resource value: 0x7f060007
            static member place_autocomplete_progress_horizontal_margin = 2131099655
            
            // aapt resource value: 0x7f060008
            static member place_autocomplete_progress_size = 2131099656
            
            // aapt resource value: 0x7f060009
            static member place_autocomplete_separator_start = 2131099657
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Drawable () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f020000
            static member places_ic_clear = 2130837504
            
            // aapt resource value: 0x7f020001
            static member places_ic_search = 2130837505
            
            // aapt resource value: 0x7f020002
            static member powered_by_google_dark = 2130837506
            
            // aapt resource value: 0x7f020003
            static member powered_by_google_light = 2130837507
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Id () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f080004
            static member place_autocomplete_clear_button = 2131230724
            
            // aapt resource value: 0x7f080006
            static member place_autocomplete_powered_by_google = 2131230726
            
            // aapt resource value: 0x7f080008
            static member place_autocomplete_prediction_primary_text = 2131230728
            
            // aapt resource value: 0x7f080009
            static member place_autocomplete_prediction_secondary_text = 2131230729
            
            // aapt resource value: 0x7f080007
            static member place_autocomplete_progress = 2131230727
            
            // aapt resource value: 0x7f080002
            static member place_autocomplete_search_button = 2131230722
            
            // aapt resource value: 0x7f080003
            static member place_autocomplete_search_input = 2131230723
            
            // aapt resource value: 0x7f080005
            static member place_autocomplete_separator = 2131230725
            
            // aapt resource value: 0x7f080000
            static member transition_current_scene = 2131230720
            
            // aapt resource value: 0x7f080001
            static member transition_scene_layoutid_cache = 2131230721
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Layout () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f040000
            static member Main = 2130968576
            
            // aapt resource value: 0x7f040001
            static member place_autocomplete_fragment = 2130968577
            
            // aapt resource value: 0x7f040002
            static member place_autocomplete_item_powered_by_google = 2130968578
            
            // aapt resource value: 0x7f040003
            static member place_autocomplete_item_prediction = 2130968579
            
            // aapt resource value: 0x7f040004
            static member place_autocomplete_progress = 2130968580
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_Mipmap () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f030000
            static member Icon = 2130903040
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)


    
    and
        
        (* partial *)Resource_String () =
            static do Android.Runtime.ResourceIdManager.UpdateIdValues()
            // aapt resource value: 0x7f070004
            static member app_name = 2131165188
            
            // aapt resource value: 0x7f070003
            static member hello = 2131165187
            
            // aapt resource value: 0x7f070002
            static member library_name = 2131165186
            
            // aapt resource value: 0x7f070000
            static member place_autocomplete_clear_button = 2131165184
            
            // aapt resource value: 0x7f070001
            static member place_autocomplete_search_hint = 2131165185
            (* Member of type 'CodeTypeConstructor' is not supported by the CodeDOM provider and was omitted *)

