// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XamarinForms.Reactive.Sample.Mars.Migrations.Migrations;

namespace XamarinForms.Reactive.Sample.Mars.Migrations.Migrations
{
    [DbContext(typeof(MigrationContext))]
    [Migration("20181231004521_EpochZero")]
    partial class EpochZero
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687");

            modelBuilder.Entity("XamarinForms.Reactive.Sample.Mars.Common.PhotoManifestDto", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<DateTime>("LandingDate");

                    b.Property<DateTime>("LaunchDate");

                    b.Property<DateTime>("MaxDate");

                    b.Property<int>("MaxSol");

                    b.Property<string>("Status");

                    b.Property<int>("TotalPhotos");

                    b.HasKey("Name");

                    b.ToTable("PhotoManifests");
                });

            modelBuilder.Entity("XamarinForms.Reactive.Sample.Mars.Common.RoverSolPhotoSetDto", b =>
                {
                    b.Property<string>("RoverName")
                        .HasMaxLength(16);

                    b.Property<int>("Sol");

                    b.Property<string>("Cameras");

                    b.Property<DateTime>("EarthDate");

                    b.Property<string>("HeadlineImage")
                        .HasMaxLength(256);

                    b.Property<int>("TotalPhotos");

                    b.HasKey("RoverName", "Sol");

                    b.ToTable("PhotoSets");
                });
#pragma warning restore 612, 618
        }
    }
}
